//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Services.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Services;

/** @hidden */
public class _ResponseReceiverPrxI extends com.zeroc.Ice._ObjectPrxI implements ResponseReceiverPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
